---
deployment:
  tasks:
    - export DEPLOYPATH=/home/u3222044/public_html/dev.pusingkuliah.com/
    - /bin/cp public/* $DEPLOYPATH
    - /bin/cp -R public/Asset $DEPLOYPATH
    - /bin/cp -R public/css $DEPLOYPATH