---
deployment:
  tasks:
    - export DEPLOYPATH=/home/u3222044/public_html/dev.pusingkuliah.com
    - /bin/cp  -R public $DEPLOYPATH
    - /bin/cp  /public/.htaccess $DEPLOYPATH
    - /bin/cp  /public/favicon.ico $DEPLOYPATH
    - /bin/cp  /public/index.php $DEPLOYPATH
    - /bin/cp  /public/robots.txt $DEPLOYPATH
    - /bin/cp  /public/web.config $DEPLOYPATH